import { NextResponse } from 'next/server'
import { PartnerProgram } from '@/lib/types'

// Extended mock partner programs database
const mockPartnerPrograms: PartnerProgram[] = [
  {
    id: 'rocketlane-1',
    vendor: 'Rocketlane',
    score: 0.84,
    maturity: 'Scaleup',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 4,
    employeeFeedback: 3,
    marketPresence: 3,
    adaptability: 3,
    summary: 'Customer Onboarding & Professional Services Automation (PSA). Excels in project delivery and client collaboration.',
    category: 'Customer Onboarding & Professional Services Automation (PSA)',
    broaderCategory: 'Project & Task Management',
    partnerTypes: ['Reseller', 'Technology Partner'],
    geography: ['North America', 'Europe'],
    compliance: ['GDPR'],
    commissionModel: '15-20%',
    onboardingTime: '3-6 months',
    supportLevel: 'High',
  },
  {
    id: 'superops-1',
    vendor: 'SuperOps',
    score: 0.81,
    maturity: 'Startup',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 4,
    employeeFeedback: 3,
    marketPresence: 2,
    adaptability: 3,
    summary: 'PSA & RMM for MSPs and IT Operations.',
    category: 'PSA & RMM for MSPs and IT Operations',
    broaderCategory: 'IT Operations / Specialized Software',
    partnerTypes: ['Technology Partner'],
    geography: ['North America', 'Europe'],
    compliance: [],
    commissionModel: '10%',
    onboardingTime: '6-12 months',
    supportLevel: 'Medium',
  },
  {
    id: 'surveysparrow-1',
    vendor: 'SurveySparrow',
    score: 0.78,
    maturity: 'Scaleup',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 4,
    employeeFeedback: 4,
    marketPresence: 3,
    adaptability: 3,
    summary: 'Experience Management, Survey & Feedback.',
    category: 'Experience Management, Survey & Feedback',
    broaderCategory: 'Business Intelligence & Analytics',
    partnerTypes: ['Technology Partner'],
    geography: ['Global'],
    compliance: ['GDPR'],
    commissionModel: '10%',
    onboardingTime: '3-6 months',
    supportLevel: 'Medium',
  },
  {
    id: 'zocket-1',
    vendor: 'Zocket',
    score: 0.77,
    maturity: 'Startup',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 4,
    employeeFeedback: 3,
    marketPresence: 2,
    adaptability: 3,
    summary: 'AdTech / Marketing Automation.',
    category: 'AdTech / Marketing Automation',
    broaderCategory: 'Marketing & Advertising',
    partnerTypes: ['Technology Partner'],
    geography: ['Asia Pacific'],
    compliance: [],
    commissionModel: '12%',
    onboardingTime: '0-3 months',
    supportLevel: 'Medium',
  },
  {
    id: 'enmovil-1',
    vendor: 'Enmovil',
    score: 0.75,
    maturity: 'Startup',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 3,
    employeeFeedback: 3,
    marketPresence: 2,
    adaptability: 4,
    summary: 'AI-powered Supply Chain & Logistics SaaS.',
    category: 'AI-powered Supply Chain & Logistics SaaS',
    broaderCategory: 'Specialized Software / AI & ML',
    partnerTypes: ['Technology Partner'],
    geography: ['Asia Pacific', 'India'],
    compliance: [],
    commissionModel: '10%',
    onboardingTime: '0-3 months',
    supportLevel: 'Medium',
  },
  {
    id: 'keka-hr-1',
    vendor: 'Keka HR',
    score: 0.83,
    maturity: 'Scaleup',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 5,
    employeeFeedback: 4,
    marketPresence: 3,
    adaptability: 3,
    summary: 'Human Resources (HR) & Payroll Management.',
    category: 'Human Resources (HR) & Payroll Management',
    broaderCategory: 'Human Resources (HR)',
    partnerTypes: ['Technology Partner'],
    geography: ['India', 'Asia Pacific'],
    compliance: [],
    commissionModel: '15%',
    onboardingTime: '6-12 months',
    supportLevel: 'High',
  },
  {
    id: 'intervue-1',
    vendor: 'Intervue',
    score: 0.74,
    maturity: 'Startup',
    health: 4,
    productFunctionality: 3,
    customerFeedback: 4,
    employeeFeedback: 3,
    marketPresence: 2,
    adaptability: 4,
    summary: 'Recruitment SaaS, ATS, Interview Management.',
    category: 'Recruitment SaaS, ATS, Interview Management',
    broaderCategory: 'Human Resources (HR)',
    partnerTypes: ['Technology Partner'],
    geography: ['Asia Pacific'],
    compliance: [],
    commissionModel: '10%',
    onboardingTime: '3-6 months',
    supportLevel: 'Medium',
  },
  {
    id: 'sendx-1',
    vendor: 'SendX',
    score: 0.73,
    maturity: 'Startup',
    health: 4,
    productFunctionality: 3,
    customerFeedback: 4,
    employeeFeedback: 3,
    marketPresence: 2,
    adaptability: 4,
    summary: 'Email Marketing Automation.',
    category: 'Email Marketing Automation',
    broaderCategory: 'Marketing & Advertising',
    partnerTypes: ['Technology Partner'],
    geography: ['North America', 'Asia Pacific'],
    compliance: [],
    commissionModel: '15%',
    onboardingTime: '0-3 months',
    supportLevel: 'Medium',
  },
  {
    id: 'wati-1',
    vendor: 'WATI',
    score: 0.72,
    maturity: 'Scaleup',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 4,
    employeeFeedback: 4,
    marketPresence: 3,
    adaptability: 3,
    summary: 'Business Messaging & Customer Engagement SaaS.',
    category: 'Business Messaging & Customer Engagement SaaS',
    broaderCategory: 'Customer Service & Support',
    partnerTypes: ['Technology Partner'],
    geography: ['Global'],
    compliance: [],
    commissionModel: '10%',
    onboardingTime: '0-3 months',
    supportLevel: 'Medium',
  },
  {
    id: 'hubspot-1',
    vendor: 'HubSpot',
    score: 0.89,
    maturity: 'Scaleup',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 5,
    employeeFeedback: 4,
    marketPresence: 5,
    adaptability: 4,
    summary: 'HubSpot\'s partner program aligns perfectly with your SMB SaaS goals, offering comprehensive marketing automation tools and strong co-selling opportunities.',
    category: 'CRM & Sales',
    partnerTypes: ['Reseller', 'ISV', 'Technology Partner'],
    geography: ['North America', 'Europe', 'Asia Pacific'],
    compliance: ['GDPR', 'SOC2'],
    commissionModel: '20-30%',
    onboardingTime: '3-6 months',
    supportLevel: 'High'
  },
  {
    id: 'salesforce-1',
    vendor: 'Salesforce',
    score: 0.85,
    maturity: 'Enterprise',
    health: 5,
    productFunctionality: 5,
    customerFeedback: 4,
    employeeFeedback: 4,
    marketPresence: 5,
    adaptability: 3,
    summary: 'Salesforce offers enterprise-grade CRM solutions with extensive partner ecosystem and strong market presence.',
    category: 'CRM & Sales',
    partnerTypes: ['Reseller', 'SI', 'ISV'],
    geography: ['North America', 'Europe', 'Asia Pacific', 'Latin America'],
    compliance: ['GDPR', 'SOC2', 'ISO 27001'],
    commissionModel: '15-25%',
    onboardingTime: '6-12 months',
    supportLevel: 'High'
  },
  {
    id: 'microsoft-1',
    vendor: 'Microsoft',
    score: 0.82,
    maturity: 'Enterprise',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 4,
    employeeFeedback: 4,
    marketPresence: 5,
    adaptability: 4,
    summary: 'Microsoft\'s partner program provides access to a comprehensive suite of business applications and cloud services.',
    category: 'Communication & Collaboration',
    partnerTypes: ['Reseller', 'SI', 'Technology Partner'],
    geography: ['North America', 'Europe', 'Asia Pacific'],
    compliance: ['GDPR', 'SOC2', 'ISO 27001', 'FedRAMP'],
    commissionModel: '10-20%',
    onboardingTime: '3-6 months',
    supportLevel: 'Medium'
  },
  {
    id: 'slack-1',
    vendor: 'Slack',
    score: 0.78,
    maturity: 'Scaleup',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 5,
    employeeFeedback: 4,
    marketPresence: 4,
    adaptability: 4,
    summary: 'Slack\'s partner program focuses on workplace communication and collaboration tools with strong integration capabilities.',
    category: 'Communication & Collaboration',
    partnerTypes: ['Technology Partner', 'ISV'],
    geography: ['North America', 'Europe'],
    compliance: ['GDPR', 'SOC2'],
    commissionModel: '15-25%',
    onboardingTime: '0-3 months',
    supportLevel: 'Medium'
  },
  {
    id: 'zoom-1',
    vendor: 'Zoom',
    score: 0.76,
    maturity: 'Scaleup',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 4,
    employeeFeedback: 3,
    marketPresence: 4,
    adaptability: 4,
    summary: 'Zoom\'s partner program offers video conferencing and communication solutions with growing market presence.',
    category: 'Communication & Collaboration',
    partnerTypes: ['Reseller', 'Technology Partner'],
    geography: ['North America', 'Europe', 'Asia Pacific'],
    compliance: ['GDPR', 'SOC2'],
    commissionModel: '10-20%',
    onboardingTime: '0-3 months',
    supportLevel: 'Medium'
  },
  {
    id: 'stripe-1',
    vendor: 'Stripe',
    score: 0.74,
    maturity: 'Scaleup',
    health: 4,
    productFunctionality: 5,
    customerFeedback: 5,
    employeeFeedback: 4,
    marketPresence: 3,
    adaptability: 5,
    summary: 'Stripe\'s partner program provides payment processing solutions with excellent developer experience and API integration.',
    category: 'Finance & Accounting',
    partnerTypes: ['Technology Partner', 'ISV'],
    geography: ['North America', 'Europe'],
    compliance: ['PCI DSS', 'SOC2'],
    commissionModel: '5-15%',
    onboardingTime: '0-3 months',
    supportLevel: 'High'
  },
  {
    id: 'atlassian-1',
    vendor: 'Atlassian',
    score: 0.72,
    maturity: 'Scaleup',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 4,
    employeeFeedback: 4,
    marketPresence: 4,
    adaptability: 4,
    summary: 'Atlassian\'s partner program offers development and collaboration tools with strong developer community support.',
    category: 'Development Tools',
    partnerTypes: ['Technology Partner', 'ISV', 'Solution Provider'],
    geography: ['North America', 'Europe', 'Asia Pacific'],
    compliance: ['SOC2', 'ISO 27001'],
    commissionModel: '10-20%',
    onboardingTime: '0-3 months',
    supportLevel: 'High'
  },
  {
    id: 'zendesk-1',
    vendor: 'Zendesk',
    score: 0.70,
    maturity: 'Scaleup',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 4,
    employeeFeedback: 3,
    marketPresence: 4,
    adaptability: 4,
    summary: 'Zendesk\'s partner program provides customer support and service solutions with comprehensive training programs.',
    category: 'Customer Support',
    partnerTypes: ['Reseller', 'Technology Partner', 'Solution Provider'],
    geography: ['North America', 'Europe', 'Asia Pacific'],
    compliance: ['GDPR', 'SOC2'],
    commissionModel: '15-25%',
    onboardingTime: '3-6 months',
    supportLevel: 'High'
  },
  {
    id: 'mailchimp-1',
    vendor: 'Mailchimp',
    score: 0.68,
    maturity: 'Scaleup',
    health: 3,
    productFunctionality: 4,
    customerFeedback: 4,
    employeeFeedback: 3,
    marketPresence: 3,
    adaptability: 4,
    summary: 'Mailchimp\'s partner program offers email marketing and automation tools with creative-focused approach.',
    category: 'Marketing Automation',
    partnerTypes: ['Technology Partner', 'Solution Provider'],
    geography: ['North America', 'Europe'],
    compliance: ['GDPR', 'SOC2'],
    commissionModel: '10-20%',
    onboardingTime: '0-3 months',
    supportLevel: 'Medium'
  },
  {
    id: 'dropbox-1',
    vendor: 'Dropbox',
    score: 0.66,
    maturity: 'Enterprise',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 4,
    employeeFeedback: 3,
    marketPresence: 4,
    adaptability: 3,
    summary: 'Dropbox\'s partner program provides file storage and collaboration solutions with enterprise focus.',
    category: 'Content Management',
    partnerTypes: ['Reseller', 'Technology Partner'],
    geography: ['North America', 'Europe', 'Asia Pacific'],
    compliance: ['GDPR', 'SOC2', 'ISO 27001'],
    commissionModel: '10-20%',
    onboardingTime: '3-6 months',
    supportLevel: 'Medium'
  },
  {
    id: 'box-1',
    vendor: 'Box',
    score: 0.64,
    maturity: 'Enterprise',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 4,
    employeeFeedback: 3,
    marketPresence: 3,
    adaptability: 3,
    summary: 'Box\'s partner program offers secure content management and collaboration with strong enterprise features.',
    category: 'Content Management',
    partnerTypes: ['Reseller', 'Technology Partner', 'Solution Provider'],
    geography: ['North America', 'Europe', 'Asia Pacific'],
    compliance: ['GDPR', 'SOC2', 'ISO 27001', 'FedRAMP'],
    commissionModel: '10-20%',
    onboardingTime: '3-6 months',
    supportLevel: 'Medium'
  },
  {
    id: 'docusign-1',
    vendor: 'DocuSign',
    score: 0.62,
    maturity: 'Enterprise',
    health: 4,
    productFunctionality: 4,
    customerFeedback: 4,
    employeeFeedback: 3,
    marketPresence: 4,
    adaptability: 3,
    summary: 'DocuSign\'s partner program provides electronic signature and document management solutions.',
    category: 'Content Management',
    partnerTypes: ['Reseller', 'Technology Partner'],
    geography: ['North America', 'Europe', 'Asia Pacific'],
    compliance: ['GDPR', 'SOC2', 'ISO 27001'],
    commissionModel: '15-25%',
    onboardingTime: '3-6 months',
    supportLevel: 'Medium'
  }
]

export async function GET() {
  try {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 500))
    
    return NextResponse.json({ 
      success: true, 
      programs: mockPartnerPrograms,
      total: mockPartnerPrograms.length
    })
    
  } catch (error) {
    console.error('Error fetching programs:', error)
    return NextResponse.json(
      { success: false, error: 'Failed to fetch programs' },
      { status: 500 }
    )
  }
}
